Update .github/workflows/publish-pacts.yaml
Co-authored-by: ichengchang <50877414+ichengchang@users.noreply.github.com>

diff --git a/.github/workflows/publish-pacts.yaml b/.github/workflows/publish-pacts.yaml
--- a/.github/workflows/publish-pacts.yaml
+++ b/.github/workflows/publish-pacts.yaml
@@ -15,6 +15,20 @@ jobs:
       new-tag: ${{ steps.tag.outputs.new_tag }}
     steps:
       - uses: actions/checkout@v3
+      - id: extract-branch
+        run: |
+          GITHUB_EVENT_NAME=${{ github.event_name }}
+          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
+            GITHUB_REF=${{ github.ref }}
+          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
+            GITHUB_REF=refs/heads/${{ github.head_ref }}
+          elif [[ "$GITHUB_EVENT_NAME" == "merge_group" ]]; then
+            GITHUB_REF=refs/heads/${{ github.head_ref }}
+          else
+            echo "Failed to extract branch information"
+            exit 1
+          fi
+          echo "repo-branch=${GITHUB_REF/refs\/heads\//""}" >> $GITHUB_OUTPUT
       - name: Set up Node
         uses: actions/setup-node@v3
         with:
